version: '3'
services:
  jenkins:
    container_name: jenkins_server
    image: dockerinpractice/jenkins
#    image: jenkins_master
    ports:
     - 8080:8080
     - 50000:50000
    volumes:
     - /home/ubuntu/jenkins:/jenkins
