version: '3'
services:
  jenkins_server:
    container_name: jenkins_server
    image: dockerinpractice/jenkins
    ports:
     - 8080:8080
     - 50000:50000
    volumes:
     - /home/ubuntu/jenkins:/jenkins
